### ISSUE TITLE
Add instructions to load local data

### ISSUE THREAD

**Issue by severo** [severo/observable-to-standalone#1]
Load local data, detecting if we serve a notebook as a local app or not. For https://github.com/severo/observable-to-standalone/tree/master/bundle_js_and_deploy.

See https://observablehq.com/d/0b7ec707d95283fe by @Fil

**Comment by severo** [comment]
@Fil: could you publish your notebook so I could link to it from the doc?

**Comment by Fil** [comment]
https://observablehq.com/@fil/standalone-app-notebook
