### ISSUE TITLE
Add an example with multiple arguments in a require() function

### ISSUE THREAD

**Issue by severo** [severo/observable-to-standalone#12]
For example:

```js
d3 = require('d3@5', 'd3-array@2')
```

**Comment by Fil** [comment]
https://github.com/Fil/SphericalContoursStandalone & https://observablehq.com/@fil/spherical-contours has `d3 = require("d3@5", "d3-geo-voronoi@1.5", "d3-geo-projection@2")`

**Comment by severo** [comment]
You're right, after double-checking, there is no particular problem or difference if require() takes various arguments.
