### ISSUE TITLE
put src/notebook in a vendor directory?

### ISSUE THREAD

**Issue by Fil** [severo/observable-to-standalone#5]
I don't like downloaded code to be mixed with main.js 

Another solution would be to put main.js in a different directory (after all it is only html/wrapper/container/glue).

**Comment by Fil** [comment]
Similar issue for main.min.js (generated) that is mixed with public/index.html (source code).

public/* could be copied to _site/ à la jekyll.

**Comment by severo** [comment]
> Similar issue for main.min.js (generated) that is mixed with public/index.html (source code).

Hmm, we better put index.html in src/, and copy it to public/ at build time. public/ is somewhat standard for that (see https://zeit.co/docs/v2/advanced/builders#static)

**Comment by severo** [comment]
And on mixing src/main.js and src/notebook/... I agree, it's weird. But I don't know if it's really a problem, or which solution would be better. We could directly extract the tgz to node_modules, but I think it's not the correct way to do.

**Comment by severo** [comment]
Done with #9
