### ISSUE TITLE
how to update the notebook

### ISSUE THREAD

**Issue by Fil** [severo/observable-to-standalone#6]
Ideally `yarn notebook && yarn serve` would update the notebook's code and serve the new version; but it seems that it's not enough currently: I have to do all of 
> rm -rf node_modules/ src/notebook/ yarn.lock
> yarn notebook && yarn

**Comment by Fil** [comment]
a bit faster:
> rm -rf node_modules/_notebook/ src/notebook/ yarn.lock

**Comment by Fil** [comment]
we also want to update the notebook without downloading the data each time

**Comment by severo** [comment]
See https://github.com/Fil/SphericalContoursStandalone/pull/12

**Comment by severo** [comment]
Done with #9
